#-------------------------------
# General Site Settings

title: Noah Loepke
description: Thinker // Tech Enthusiast // Student
email: loepke.2@osu.edu

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  Hi, my name is Noah! One of my biggest passions is nature, which is why I spend most of my time outdoors, even when coding! 
  My favorite outdoor hobbies include hiking, tennis, archery, and skating. While relaxing inside however, I enjoy reading 
  books, playing video games, and tinkering with various programs on my computer. Technology has always fascinated me and the 
  rapidly changing industry keeps me on my toes constantly.




skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '6'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '5'}
- {name: Teamwork, value: '9'}
- {name: Programming, value: '6'}

#-------------------------------

#-------------------------------
# Client Section
#-------------------------------
# Contact Section

social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/noah-loepke-58456714a/'}
- {icon: 'facebook', link: 'https://www.facebook.com/noahloepke'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
